//! The generated-file header.
//!
//! Every rendered overlay begins with a machine-readable marker line carrying
//! the context hash (so `refresh` can detect "nothing changed"), a human block
//! describing provenance, and a visible warning that the file is generated and
//! is **guidance, not policy**.

/// Prefix of the machine-readable first line of every generated file.
pub const GENERATED_MARKER: &str = "<!-- rosita:generated";

/// Metadata rendered into the header.
pub struct HeaderMeta<'a> {
    /// RFC3339 generation timestamp.
    pub generated_at: &'a str,
    /// Host the snapshot was generated on.
    pub host: &'a str,
    /// Agent id (`claude`/`codex`/`gemini`/…).
    pub agent: &'a str,
    /// Selected profile name.
    pub profile: &'a str,
    /// `sha256:…` context hash.
    pub context_hash: &'a str,
    /// Where the base template came from.
    pub template_source: &'a str,
    /// Config files that contributed (display strings).
    pub sources: &'a [String],
}

/// Build the full header block (ends with a trailing blank line).
///
/// Includes a **self-healing** banner: it tells the agent when/where the
/// snapshot was made and the exact commands to verify, refresh, or remove it —
/// plus the `$ROSITA_RUN` signal so an agent launched via `rosita run` knows the
/// context is current, and one launched directly knows to check freshness.
pub fn build(meta: &HeaderMeta) -> String {
    let sources = if meta.sources.is_empty() {
        "(built-in defaults only)".to_string()
    } else {
        meta.sources.join(", ")
    };
    format!(
        "{GENERATED_MARKER} context={hash} -->\n\
         <!--\n\
         \x20 GENERATED BY rosita — DO NOT EDIT BY HAND.\n\
         \x20 generated : {generated_at}\n\
         \x20 host      : {host}\n\
         \x20 agent     : {agent}\n\
         \x20 profile   : {profile}\n\
         \x20 context   : {hash}\n\
         \x20 template  : {template}\n\
         \x20 sources   : {sources}\n\
         -->\n\
         \n\
         > 🕒 rosita snapshot — **{host}**, **{generated_at}**, profile **{profile}** (context {hash}).\n\
         > This is point-in-time **agent guidance, not enforced policy**, and may be stale.\n\
         > Check freshness with `rosita doctor`; regenerate with `rosita refresh`; remove with `rosita clean`.\n\
         > If `$ROSITA_RUN` is unset and the project changed since the time above, refresh before relying on this.\n\
         \n",
        hash = meta.context_hash,
        generated_at = meta.generated_at,
        host = meta.host,
        agent = meta.agent,
        profile = meta.profile,
        template = meta.template_source,
        sources = sources,
    )
}

/// Extract the `context=sha256:…` hash from a previously generated file, if any.
///
/// Scans every line for the marker (not just the first) so it also works when
/// the generated block is inlined inside a larger user-owned file (e.g. the
/// Codex `AGENTS.override.md`).
pub fn extract_context_hash(content: &str) -> Option<String> {
    for line in content.lines() {
        let Some(rest) = line.trim_start().strip_prefix(GENERATED_MARKER) else {
            continue;
        };
        let Some(token) = rest.trim_start().strip_prefix("context=") else {
            continue;
        };
        let hash: String = token.chars().take_while(|c| !c.is_whitespace()).collect();
        if !hash.is_empty() {
            return Some(hash);
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> String {
        build(&HeaderMeta {
            generated_at: "2026-05-29T13:35:56Z",
            host: "mac-air",
            agent: "claude",
            profile: "rust",
            context_hash: "sha256:abcdef1234567890",
            template_source: "embedded",
            sources: &[".rosita/config.toml".to_string()],
        })
    }

    #[test]
    fn header_contains_fields_and_self_healing_banner() {
        let h = sample();
        assert!(h.starts_with(GENERATED_MARKER));
        assert!(h.contains("profile   : rust"));
        assert!(h.contains("agent     : claude"));
        assert!(h.contains("host      : mac-air"));
        assert!(h.contains("DO NOT EDIT"));
        assert!(h.contains("not enforced policy"));
        // self-healing instructions + launch-mode signal
        assert!(h.contains("rosita refresh"));
        assert!(h.contains("rosita clean"));
        assert!(h.contains("$ROSITA_RUN"));
    }

    #[test]
    fn roundtrips_context_hash() {
        let h = sample();
        assert_eq!(
            extract_context_hash(&h).as_deref(),
            Some("sha256:abcdef1234567890")
        );
    }

    #[test]
    fn no_hash_when_absent() {
        assert_eq!(extract_context_hash("# just a file\n"), None);
        assert_eq!(extract_context_hash(""), None);
    }
}
